In [2]:
import sknn.mlp
import sklearn.metrics
import pandas as pd
print 'Hi!'
import matplotlib.pyplot as plt

Hi!


In [3]:
df= pd.read_csv('DataSets/New_Mod_1.csv',sep=',')

In [4]:
from sklearn.cross_validation import train_test_split

train, test = train_test_split(df, test_size = 0.3)

In [5]:
Y_train = train.pop('apnea')
X_train = train

In [6]:
Y_test= test.pop('apnea')
X_test= test

In [7]:
print X_train

     Gestation  AGASGA  SURFACTANT   BWT  STEROIDS  HC_Birth  HC_4WEEKS  \
197         30       1           1  1570         1      28.2      29.00   
276         31       1           1  1165         4      28.0    2200.00   
39          27       1           2   740         2      20.5      23.00   
318         32       2           2  1015         4      23.0      24.00   
139         31       1           1  1570         3      30.0      29.00   
320         31       2           2   895         3      26.0      27.50   
16          28       1           2  1365         2      28.0      31.00   
243         28       1           2   915         1      25.5      38.43   
219         28       1           2  1085         4      27.0      38.43   
79          31       1           1  1755         4      31.0      33.00   
61          30       1           1  1310         3      28.0      30.00   
339         30       1           2  1270         3      28.0      38.43   
46          29       2   

# Preprocessing of the Data

In [8]:
from sklearn import preprocessing
X_train=X_train.values
X_test=X_test.values
Y_train=Y_train.values
Y_test=Y_test.values

X_train = preprocessing.MinMaxScaler().fit_transform(X_train)
X_test = preprocessing.MinMaxScaler().fit_transform(X_test)
Y_train = preprocessing.MinMaxScaler().fit_transform(Y_train)
Y_test = preprocessing.MinMaxScaler().fit_transform(Y_test)

D:\Anaconda3\envs\dato-env\lib\site-packages\sklearn\utils\validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
D:\Anaconda3\envs\dato-env\lib\site-packages\sklearn\preprocessing\data.py:324: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
D:\Anaconda3\envs\dato-env\lib\site-packages\sklearn\preprocessing\data.py:359: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
D:\Anaconda3\envs\dato-env\lib\site-pac

In [32]:
for r in X_test:
    print r

[ 0.63636364  0.          0.          0.45074627  1.          0.56521739
  0.51847051  0.          0.5         0.5         0.          0.          0.
  0.          0.          0.          0.          0.125       0.          0.
  0.12345679]
[ 0.54545455  0.5         0.          0.19104478  0.33333333  0.39130435
  1.          1.          0.          0.5         0.5         1.          0.
  0.          0.          0.          0.          0.0625      1.          1.
  0.0617284 ]
[ 0.63636364  0.5         1.          0.36119403  0.66666667  0.39130435
  0.25923526  0.          0.5         0.5         0.          0.          0.16
  0.          0.          0.          0.05882353  0.025       0.          1.
  0.03703704]
[ 0.81818182  0.5         0.          0.22089552  1.          0.56521739
  1.          0.          0.          0.5         0.5         1.          0.
  0.          0.          0.          0.11764706  0.1         0.14285714
  1.          0.12345679]
[ 0.81818182  0.          

In [9]:
from sknn.mlp import Classifier, Layer

nn = Classifier(
    layers=[
        Layer("Sigmoid", units=20),
        Layer("Sigmoid", units=10),
         Layer("Sigmoid", units=5),
        Layer("Softmax")],
    learning_rate=0.001,
    n_iter=100)
nn.fit(X_train, Y_train)

D:\Anaconda3\envs\dato-env\lib\site-packages\theano\tensor\signal\downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


Classifier(batch_size=1, callback=None, debug=False, dropout_rate=None,
      f_stable=0.001,
      hidden0=<sknn.nn.Layer `Sigmoid`: units=20, name=u'hidden0', frozen=False>,
      hidden1=<sknn.nn.Layer `Sigmoid`: units=10, name=u'hidden1', frozen=False>,
      hidden2=<sknn.nn.Layer `Sigmoid`: units=5, name=u'hidden2', frozen=False>,
      layers=[<sknn.nn.Layer `Sigmoid`: units=20, name=u'hidden0', frozen=False>, <sknn.nn.Layer `Sigmoid`: units=10, name=u'hidden1', frozen=False>, <sknn.nn.Layer `Sigmoid`: units=5, name=u'hidden2', frozen=False>, <sknn.nn.Layer `Softmax`: units=2L, name=u'output', frozen=False>],
      learning_momentum=0.9, learning_rate=0.001, learning_rule=u'sgd',
      loss_type=None, n_iter=100, n_stable=10,
      output=<sknn.nn.Layer `Softmax`: units=2L, name=u'output', frozen=False>,
      random_state=None, regularize=None, valid_set=None, valid_size=0.0,
      verbose=None, warning=None, weight_decay=None, weights=None)

In [389]:
Y_test

array([ 1.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,
        1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [390]:
score = nn.score(X_test, Y_test)

In [391]:
score

0.72072072072072069

In [392]:
y_predicted = nn.predict(X_test)

In [393]:
print y_predicted

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [394]:
y_predic=y_predicted.flatten()

In [395]:
import numpy as np
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(y_predic,Y_test, pos_label=0)

In [396]:
fpr


array([ nan,  nan])

In [397]:
tpr

array([ 0.27927928,  1.        ])

In [398]:
import matplotlib.pyplot as plt
import numpy as np
# false_positive_rate 
# true_positive_rate 

# This is the ROC curve
plt.plot(tpr,fpr)
plt.show() 


In [399]:
# This is the AUC
roc_auc = np.trapz(fpr,tpr)

In [400]:
plt.figure()
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver operating characteristic example')
plt.legend(loc="lower right")
plt.show()